pipeline {
    agent any


    environment {
        registry = "index.docker.io/v1/"
        dockerCreds = credentials('dockerhub-credentials') // Reference the ID of your Jenkins credentials here
    }
    stages {
        // stage('Build Backend') {
        //     steps {
        //         script {
        //             docker.build('mern-backend', 'backend')
        //         }
        //     }
        // }
        stage('Build Backend') {
            steps {
                // Build Docker image for backend
                script {
                    def backendPath = "basic-erp/backend"

                    // Check if the directory exists
                    if (fileExists(backendPath)) {
                        // Build Docker image
                        bat "docker build -t mern-backend ${backendPath}"
                    } else {
                        error "Backend directory ${backendPath} not found"
                    }
                }
            }
        }
        // stage('Build Frontend') {
        //     steps {
        //         script {
        //             docker.build('mern-frontend', 'frontend')
        //         }
        //     }
        // }

         stage('Build Frontend') {
            steps {
                // Build Docker image for frontend
                script {
                    def frontendPath = "basic-erp/frontend"

                    // Check if the directory exists
                    if (fileExists(frontendPath)) {
                        // Build Docker image
                        bat "docker build -t mern-frontend ${frontendPath}"
                    } else {
                        error "Frontend directory ${frontendPath} not found"
                    }
                }
            }
        }
        stage('Push Backend') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image('mern-backend').push('latest')
                    }
                }
            }
        }
        stage('Push Frontend') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image('mern-frontend').push('latest')
                    }
                }
            }
        }
    }
}
